### ISSUE TITLE
Create DB design ERD

### ISSUE THREAD

**Issue by umairwaheed** [fecundityllc/trackit#1]

**Comment by Malik-Muneeb** [comment]
@umairwaheed Kindly take a look on ER diagram. Is it fine ?
![Blank diagram](https://user-images.githubusercontent.com/47572370/94659158-4ca8d500-031d-11eb-807e-9aad606abbc1.png)

**Comment by umairwaheed** [comment]
I think we should add one more table. **Issue**

Issue
-----------
issue_url
issue_title

**Comment by Malik-Muneeb** [comment]
Agreed. let me modify it

**Comment by Malik-Muneeb** [comment]
How is it now?
![Blank diagram (3)](https://user-images.githubusercontent.com/47572370/94667340-289ec100-0328-11eb-887d-28facc14a321.png)

**Comment by umairwaheed** [comment]
This looks good. I would add title of the issue in IssueDetails as well.

**Comment by umairwaheed** [comment]
So once you have updated the design. You can move to the next task.

**Comment by Malik-Muneeb** [comment]
**Added issue_title as well. Moving towards next task**
![Blank diagram (4)](https://user-images.githubusercontent.com/47572370/94763970-2722d680-03c4-11eb-9427-80924c79774e.png)
