### ISSUE TITLE
Create MVP scope document.

### ISSUE THREAD

**Issue by umairwaheed** [fecundityllc/trackit#2]
Identify the scope of work that you are planning to do in the MVP. For example,

- structure of the slack command
- technology stack
- define each argument of the slack command
- how will you use GitHub API.

**Comment by umairwaheed** [comment]
The document should be such that any new collaborator should be able to start work on the project after looking at it.

**Comment by umairwaheed** [comment]
You can use GitHub Wiki to create your scope document.

**Comment by Malik-Muneeb** [comment]
@umairwaheed - I created a Github Wiki document to define the scope of work. Kindly review it.

**Comment by umairwaheed** [comment]
Looks great. https://github.com/fecundityllc/trackit/wiki/MVP-Scope-Document
